# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Export Apple UDIDs"
  lane :export_udids do
    root = Dir.pwd

    firebase_app_distribution_get_udids(
        app: ENV["APP_ID"],
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        output_file: "#{path}/tester-udids.txt",
    )
  end

  desc "Register devices"
  lane :register_devices do
    root = Dir.pwd
    file = "#{root}/tester-udids.txt"

    if Dir.exist? file
      register_devices(
        devices_file: file
      )
  end
end
