# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Import Apple UDIDs"
  lane :import_udids do
    root = Dir.pwd
    file = "#{root}/tester-udids.txt"

    firebase_app_distribution_get_udids(
        app: ENV["APP_ID"],
        firebase_cli_token: ENV["FIREBASE_TOKEN"],
        output_file: file,
    )

    if File.file?(file)
      puts "directory exists #{file}"
      register_devices(
        devices_file: file
      )
    end
  end
end
