name: "Setup flutter sdk"
description: "Setup flutter sdk"
branding:
  icon: "maximize"
  color: "blue"
inputs:
  flutter-channel:
    description: "Flutter channel"
    required: false
    default: "stable"
  flutter-version:
    description: "Flutter version"
    required: false
    default: "any"
  # jdk-dist:
  #   description: "JDK distribution"
  #   required: false
  #   default: "adopt"
  # jdk-version:
  #   description: "JDK version"
  #   required: false
  #   default: "stable"
outputs:
  flutter-cache-key:
    description: "Flutter sdk cache key"
    value: ${{ steps.flutter-sdk-setup.outputs.cache-key }}
  flutter-cache-path:
    description: "Flutter sdk cache path"
    value: ${{ steps.flutter-sdk-setup.outputs.cache-path }}
runs:
  using: "composite"
  steps:
    # - name: Setup jdk
    #   uses: actions/setup-java@v3
    #   with:
    #     distribution: ${{ inputs.jdk-dist }}
    #     java-version: ${{ inputs.jdk-version }}
    # - name: Setup android SDK
    #   uses: android-actions/setup-android@v2
    - name: Print inputs
      run: echo "${{ toJSON(inputs) }}"
      shell: bashs
    - id: flutter-sdk-setup
      name: Setup flutter sdk
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: ${{ inputs.flutter-channel }}
        cache: false
    - name: Print flutter-sdk-setup outputs
      run: echo ${{ toJSON(steps.flutter-sdk-setup.outputs) }}
      shell: bash
    - name: Install dependencies
      run: |
        flutter pub global activate very_good_cli
        very_good --analytics false
        very_good packages get --recursive
      shell: bash
    - name: Check flutter sdk
      run: flutter doctor -v
      shell: bash
