# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Fastlane deploy android"
  lane :distribute_firebase do |options|
      puts options
      puts ENV["APP_ID"]

      begin
        firebase_app_distribution(
          app: ENV["APP_ID"],
          # firebase_cli_token: ENV["FIREBASE_TOKEN"],
          service_credentials_file: options[:credentials_file],
          android_artifact_type: options[:artifact_type].upcase,
          android_artifact_path: options[:artifact_path]
        )

        upload_to_play_store(
          release_status: 'draft',
          track: 'internal',
          json_key: options[:credentials_file],
          aab: options[:artifact_path],
          skip_upload_metadata: true,
          skip_upload_changelogs: true,
          skip_upload_images: true,
          skip_upload_screenshots: true,
        )
      rescue => e
        puts "Rescued: #{e.inspect}"
        raise
      end
  end

  desc "Fastlane get app distribution latest release"
  lane :get_appdist_latest_release do |options|
      begin
        puts options
        puts ENV["APP_ID"]
                
        release = firebase_app_distribution_get_latest_release(
          app: ENV['APP_ID'],
          service_credentials_file: options[:credentials_file], 
        )

        puts release
        version = release[:displayVersion]
        build = release[:buildVersion]

        sh("echo \"version=#{version}\" >> $GITHUB_ENV")
        sh("echo \"build=#{build}\" >> $GITHUB_ENV")
      rescue => e
        puts "Rescued: #{e.inspect}"
        raise
      end
  end

  desc "Fastlane get google play track latest release"
  lane :get_playstore_latest_release do |options|
      begin
        puts options
        puts ENV["APP_ID"]
                
        version = google_play_track_release_names(
          app: ENV['APP_ID'],
          service_credentials_file: options[:credentials_file], 
        )
        build = google_play_track_version_codes(
          app: ENV['APP_ID'],
          service_credentials_file: options[:credentials_file], 
        )

        puts version
        puts build

        sh("echo \"version=#{version}\" >> $GITHUB_ENV")
        sh("echo \"build=#{build}\" >> $GITHUB_ENV")
      rescue => e
        puts "Rescued: #{e.inspect}"
        raise
      end
  end
end