# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Fastlane deploy android"
  lane :distribute_firebase do |options|
      puts options
      puts ENV["APP_ID"]

      begin
        firebase_app_distribution(
          app: ENV["APP_ID"],
          # firebase_cli_token: ENV["FIREBASE_TOKEN"],
          service_credentials_file: options[:credentials_file],
          android_artifact_type: options[:artifact_type].upcase,
          android_artifact_path: options[:artifact_path]
        )

        upload_to_play_store(
          track: 'internal',
          json_key: options[:credentials_file],
          aab: options[:artifact_path],
          changes_not_sent_for_review: true,
        )
      rescue => e
        puts "Rescued: #{e.inspect}"
        raise
      end
  end
end