name: github_actions
on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/flutter_package.yml
    with:
      coverage_excludes: "*.g.dart *.freezed.dart"
      flutter_channel: beta
      flutter_version: 3.1.0
      runs_on: self-hosted
