name: github_actions
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
      flutter_channel:
        description: "Flutter channel"
        type: choice
        default: stable
        required: false
        options:
          - master
          - beta
          - stable
      flutter_version:
        description: "Flutter version"
        type: string
        default: "3.3.2"
        required: false
  workflow_call:
    # secrets:
    #   DART_DEFINED_VAR1:
    #     required: true
    inputs:
      environment:
        required: true
        type: string

      flutter_channel:
        required: false
        type: string
        default: "stable"
      flutter_version:
        required: false
        type: string
        default: "3.3.2"

env:
  DART_DEFINED_VAR1: "var1"
  DART_DEFINED_VAR2: "var2"

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Print env
        run: echo ${{toJSON(env)}}
      - name: Print env
        run: printenv
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Setup flutter
      #   uses: ./.github/actions/setup-flutter
      # - name: Check flutter sdk
      #   run: flutter doctor

  # analyze:
  #   runs-on: self-hosted
  #   needs: setup
  #   steps:
  #     - name: Setup flutter
  #       uses: ./.github/actions/setup-flutter
  #     - name: Check formatting
  #       # run: flutter format --set-exit-if-changed lib test
  #       run: flutter format lib test
  #     - name: Analyze
  #       run: flutter analyze lib test

  # test:
  #   runs-on: self-hosted
  #   needs: setup
  #   steps:
  #     - name: Run Tests
  #       run: very_good test -j ${{inputs.concurrency}} ${{(inputs.test_recursion && '--recursive') || ''}} ${{(inputs.test_optimization && '--optimization') || '--no-optimization'}} --coverage --test-randomize-ordering-seed random

  # build:
  #   runs-on: self-hosted
  #   environment: inputs.environment
  #   needs:
  #     - setup
  #     - analyze
  #     # - test
  #   steps:
  #     - name: Setup flutter
  #       uses: ./.github/actions/setup-flutter
  #     - name: Build appbundle
  #       run: flutter build appbundle --flavor staging --obfuscate --split-debug-info=debug_info --dart-define=DART_DEFINED_VAR1={{env.DART_DEFINED_VAR1}}
# with:
#   coverage_excludes: "*.g.dart *.freezed.dart"
#   flutter_channel: beta
#   flutter_version: 3.1.0
#   runs_on: self-hosted
#
