name: github_actions
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  matrix:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: mafiapigs-macos
            metaId: 2177361
            otherId: 2177360
          - target: project-windows
            metaId: 2177362
            otherId: 2177360
    steps:
      # - name: Print conditions
      #   run: |
      #     echo "github.event.inputs.build_target: ${{ github.event.inputs.build_target }}"
      #     echo "github.event_name: ${{ github.event_name }}"
      - run: |
          echo "${{ toJSON(matrix) }}"

          # matrix=$((
          #   echo '${{ toJSON(matrix) }}'
          # ) | jq -c .)

          matrix=$(jq -c . <<<"${{ toJSON(matrix) }}")

          echo "$matrix"
          echo "$matrix" > matrix
          cat matrix
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        id: matrix
        # if: github.event_name == 'workflow_dispatch' && (github.event.inputs.build_target == matrix.target || github.event.inputs.build_target == '*' || github.event.inputs.build_target == '')
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ hashFiles('matrix') || 'none' }}
          path: matrix
          if-no-files-found: warn

  check-matrix:
    runs-on: self-hosted
    needs: [matrix]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          matrix="$(cat */matrix | jq -c --slurp .)"
          echo "$matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
        id: matrix
      - uses: lhotari/action-upterm@v1

  steam:
    name: "Release ${{ matrix.includes.target }}"
    needs: [check-matrix]
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        includes: ${{ fromJSON(needs.check-matrix.outputs.matrix) }}
    steps:
      - name: Print matrix
        run: |
          echo "${{ toJSON(matrix) }}"
