name: github_actions
on:
  push:
    branches:
      - master
      - develop
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
      flutter-channel:
        description: "Flutter channel"
        type: choice
        default: stable
        required: false
        options:
          - master
          - beta
          - stable
      flutter-version:
        description: "Flutter version"
        type: string
        default: "3.3.2"
        required: false
      jdk-dist:
        description: "JDK distribution"
        required: false
        default: "adopt"
      jdk-version:
        description: "JDK version"
        required: false
        default: "11"
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      flutter-channel:
        required: false
        type: string
        default: "stable"
      flutter-version:
        required: false
        type: string
        default: "3.3.2"
      jdk-dist:
        required: false
        type: string
        default: "adopt"
      jdk-version:
        required: false
        type: string
        default: "11"

jobs:
  setup:
    strategy:
      fail-fast: true
      matrix:
        os:
          - self-hosted-ubuntu
          - self-hosted-macos
    runs-on: ${{ matrix.os }}
    outputs:
      flutter-channel: ${{ env.flutter_channel }}
      flutter-version: ${{ env.flutter_version }}
      jdk-dist: ${{ env.jdk_dist }}
      jdk-version: ${{ env.jdk_version }}
      tag-annotation: ${{ env.tag_annotation }}
      platform: ${{ env.platform }}
    steps:
      # - name: Print github context
      #   run: echo "${{ toJSON(github) }}"
      - name: Print env
        run: echo "${{ toJSON(env) }}"
      - name: Print secrets
        run: echo "${{ toJSON(secrets) }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Force fetch tag annotations
        run: git fetch --tags --force
      - id: parse-var
        name: Parse variables
        run: |
          flutter_channel="${{ inputs.flutter-channel || 'stable' }}"
          flutter_version="${{ inputs.flutter-version || '3.3.2' }}"
          jdk_dist="${{ inputs.jdk-dist || 'adopt' }}"
          jdk_version="${{ inputs.jdk-version || '11' }}"
          platform="${{ matrix.build == 'ipa' && 'ios' || 'android'}}"

          if [[ "${{ github.ref_type }}" == "tag" ]]
          then
            tag_annotation=$(git tag -l --format="%(contents)" ${{ github.ref_name }})
            echo "tag_annotation=$tag_annotation" >> $GITHUB_ENV
            echo $tag_annotation
          fi

          echo "flutter_channel=$flutter_channel" >> $GITHUB_ENV
          echo "flutter_version=$flutter_version" >> $GITHUB_ENV
          echo "jdk_dist=$jdk_dist" >> $GITHUB_ENV
          echo "jdk_version=$jdk_version" >> $GITHUB_ENV
          echo "platform=$platform" >> $GITHUB_ENV

          echo $flutter_channel
          echo $flutter_version
          echo $jdk_dist
          echo $jdk_version
          echo $platform
  # analyze:
  #   runs-on: self-hosted
  #   needs: setup
  #   steps:
  #     - name: Print setup outputs
  #       run: echo "${{ toJSON(needs.setup.outputs) }}"
  #     - id: flutter-sdk-setup
  #       name: Setup flutter sdk
  #       uses: ./.github/actions/setup-flutter
  #       with:
  #         flutter-channel: ${{ needs.setup.outputs.flutter-channel }}
  #         flutter-version: ${{ needs.setup.outputs.flutter-version }}
  #     - name: Check formatting
  #       # run: flutter format --set-exit-if-changed lib test
  #       run: flutter format lib test
  #     - name: Analyze
  #       run: flutter analyze lib test

  # test:
  #   runs-on: self-hosted
  #   needs: setup
  #   steps:
  #     - name: Run Tests
  #       run: very_good test -j ${{inputs.concurrency}} ${{(inputs.test_recursion && '--recursive') || ''}} ${{(inputs.test_optimization && '--optimization') || '--no-optimization'}} --coverage --test-randomize-ordering-seed random

  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          # - build: apk
          #   environment: development
          # - build: apk
          #   environment: staging
          # - build: apk
          #   environment: production
          # - build: appbundle
          #   environment: development
          # - build: appbundle
          #   environment: staging
          - build: appbundle
            environment: production
          # - build: ipa
          #   environment: development
          # - build: ipa
          #   environment: staging
          # - build: ipa
          #   environment: production
    # runs-on: self-hosted
    runs-on: ${{ matrix.build == 'ipa' && 'self-hosted-macos' || 'self-hosted' }}
    environment: ${{ matrix.environment }}
    needs:
      - setup
      # - analyze
      # - test
    steps:
      - name: Print setup outputs
        run: |
          echo "outputs: ${{ toJSON(needs.setup.outputs) }}"
          echo "env: ${{ toJSON(needs.setup.env) }}"
      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: ${{ needs.setup.outputs.jdk-dist }}
          java-version: ${{ needs.setup.outputs.jdk-version }}
      - name: Setup android sdk
        uses: android-actions/setup-android@v2
      - id: flutter-sdk-setup
        name: Setup flutter sdk
        uses: ./.github/actions/setup-flutter
        with:
          flutter-channel: ${{ needs.setup.outputs.flutter-channel }}
          flutter-version: ${{ needs.setup.outputs.flutter-version }}
      - name: Create version.yml
        run: |
          major=0
          minor=0
          patch=0

          if [[ "${{ github.ref_type }}" == "tag" ]]
          then
            if [[ ${{ github.ref_name }} =~ ([0-9]+)+.([0-9]+)+.([0-9]+)+ ]]
            then
              major=${BASH_REMATCH[1]}
              minor=${BASH_REMATCH[2]}
              patch=${BASH_REMATCH[3]}
            fi
          fi

          cat << EOF > version.yml
          ---
          major: $major
          minor: $minor
          patch: $patch
          EOF
      - name: Create keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" > android/release.jks.asc
          gpg -d --passphrase ${{ secrets.KEYSTORE_PASSPHRASE }} --batch android/release.jks.asc > android/release.jks
      - name: Create key.properties
        run: |
          cat << EOF > android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ALIAS_PASSWORD }}
          keyAlias=${{ secrets.KEYSTORE_ALIAS }}
          storeFile=${{ github.workspace }}/android/release.jks
          EOF
      - name: "Create alias to 'bundle exec fastlane'"
        run: alias fastlane="bundle exec fastlane"
      - name: "Run 'bundle install'"
        working-directory: ./${{ needs.setup.outputs.platform }}
        run: bundle install
      - name: Sync version with tag
        working-directory: ./${{ needs.setup.outputs.platform }}
        run: fastlane run flutter_version_manager yml:${{ github.workspace }}/version.yml pubspec:${{ github.workspace }}/pubspec.yml arguments:-apply
      - name: Build ${{ matrix.environment }} ${{ matrix.build }}
        run: |
          flutter build ${{ matrix.build }} \
          --flavor ${{ matrix.environment }} \
          --obfuscate \
          --split-debug-info=debug_info \
          --dart-define=MONGODB_USERNAME=${{secrets.MONGODB_USERNAME}} \
          --dart-define=MONGODB_PASSWORD=${{secrets.MONGODB_PASSWORD}} \
          --dart-define=MAPBOX_TOKEN=${{secrets.MAPBOX_TOKEN}} \
          --dart-define=DEEPLINK_CHECKSUM=${{secrets.DEEPLINK_CHECKSUM}} \
          --dart-define=ONE_SIGNAL_APP_ID=${{secrets.ONE_SIGNAL_APP_ID}}
      - name: Upload ${{ matrix.environment }} ${{ matrix.build }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.environment }}-${{ matrix.build }}
          path: |
            ${{ github.workspace }}/build/app/outputs/bundle/${{ matrix.environment }}Release/app-${{ matrix.environment }}-release.aab
            ${{ github.workspace }}/build/app/outputs/flutter-apk/app-${{ matrix.environment }}-release.apk
            ${{ github.workspace }}/build/ios/ipa/*.ipa
          if-no-files-found: error

  deploy:
    strategy:
      fail-fast: true
      matrix:
        include:
          # - build: apk
          #   environment: development
          # - build: apk
          #   environment: staging
          # - build: apk
          #   environment: production
          # - build: appbundle
          #   environment: development
          # - build: appbundle
          #   environment: staging
          - build: appbundle
            environment: production
          # - build: ipa
          #   environment: development
          # - build: ipa
          #   environment: staging
          # - build: ipa
          #   environment: production
    runs-on: ${{ matrix.build == 'ipa' && 'self-hosted-macos' || 'self-hosted' }}
    environment: ${{ matrix.environment }}
    needs:
      - setup
      - build
    steps:
      - id: parse-var
        name: Parse variables
        run: |
          platform="${{ matrix.build == 'ipa' && 'ios' || 'android'}}"
          artifact_path=${{ github.workspace }}/build

          case "${{ matrix.build }}" in
            "appbundle")
              artifact_file=${{ github.workspace }}/build/app/outputs/bundle/${{ matrix.environment }}Release/app-${{ matrix.environment }}-release.aab
              ;;

            "apk")
              artifact_file=${{ github.workspace }}/build/app/outputs/flutter-apk/app-${{ matrix.environment }}-release.apk
              ;;

            "ipa")
              artifact_file=${{ github.workspace }}/build/ios/ipa/app-${{ matrix.environment }}.ipa
              # artifact_file=${{ github.workspace }}/build/ios/ipa/flutter_github_actions.ipa
              ;;

            *) 
              ;;
          esac

          echo "platform=$platform" >> $GITHUB_OUTPUT
          echo "artifact_path=$artifact_path" >> $GITHUB_OUTPUT
          echo "artifact_file=$artifact_file" >> $GITHUB_OUTPUT

          echo $platform
          echo $artifact_path
          echo $artifact_file
      # - if: ${{ steps.parse-var.outputs.platform == 'android' }}
      - id: create-credentials
        name: Create google play credentials
        working-directory: ./${{ steps.parse-var.outputs.platform }}
        run: |
          echo "${{ secrets.APP_DIST_CREDENTIALS }}" > app-dist-credentials.json.asc
          gpg -d --passphrase ${{ secrets.APP_DIST_CREDENTIALS_PASSPHRASE }} --batch app-dist-credentials.json.asc > app-dist-credentials.json
          echo "::set-output name=app-dist-credentials::$(pwd)/app-dist-credentials.json"
      - name: "Create alias to 'bundle exec fastlane'"
        run: alias fastlane="bundle exec fastlane"
      - name: "Run 'bundle install'"
        working-directory: ./${{ steps.parse-var.outputs.platform }}
        run: bundle install
      - id: download-artifact
        name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.environment }}-${{ matrix.build }}
          path: ${{ steps.parse-var.outputs.artifact_path }}
      # - if: ${{ steps.parse-var.outputs.platform == 'ios' }}
      #   working-directory: ./${{ steps.parse-var.outputs.platform }}
      #   name: Import Apple UDIDs
      # env:
      #   APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}
      #   FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #   FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
      #   run: fastlane import_udids
      # - name: Deploy with fastlane
      #   working-directory: ./${{ steps.parse-var.outputs.platform }}
      #   env:
      #     APP_ID: ${{ steps.parse-var.outputs.platform == 'ios' && secrets.IOS_FIREBASE_APP_ID || secrets.ANDROID_FIREBASE_APP_ID }}
      #   run: |
      #     fastlane distribute_firebase \
      #     artifact_type:${{ matrix.build == 'appbundle' && 'aab' || matrix.build }} \
      #     artifact_path:${{ steps.parse-var.outputs.artifact_file }} \
      #     credentials_file:${{ steps.create-credentials.outputs.app-dist-credentials }}
      #     # ${{ steps.parse-var.outputs.platform == 'android' && format('credentials_file:{0}', steps.create-credentials.outputs.app-dist-credentials) || '' }}
# build/app/outputs/bundle/release/app-release.aab
# build/app/outputs/bundle/developmentRelease/app-development-release.aab
# build/app/outputs/bundle/stagingRelease/app-staging-release.aab
# build/app/outputs/bundle/productionRelease/app-production-release.aab
# build/app/outputs/flutter-apk/app-release.apk
# build/app/outputs/flutter-apk/app-development-release.apk
# build/app/outputs/flutter-apk/app-staging-release.apk
# build/app/outputs/flutter-apk/app-production-release.apk
# build/ios/archive/Runner.xcarchive
# build/ios/ipa/*.ipa
